Adiciona fuitile.logger para diagnostico do tempo durante basic_pipeline
parlametria/leggoR pull request #690
Opened 2021-04-28 18:05 UTC by joaolgm

2021-05-04 16:43 UTC, jeffersonrpn approved these changes

2021-05-05 21:01 UTC, gileadekelvin requested changes

2021-05-05 21:01 UTC, gileadekelvin commented on Dockerfile
> +RUN if [ "$clone_rcongresso" = "false" ] ;  then Rscript -e 'devtools::install("rcongresso/", quiet=TRUE)'; else Rscript -e 'devtools::install_github("analytics-ufcg/rcongresso", quiet=TRUE)'; fi
Eu acho que seria uma boa manter os logs dessa instalação no build. Acredito que a modificação de remover o comando de instalação dos scripts nos outros arquivos modificados já ajuda a limpar bastante o log dos pacotes no meio do processamento.

Minha sugestão é não adicionar o quiet=TRUE no dockerfile

2021-05-05 21:01 UTC, gileadekelvin commented on scripts/utils-hora.R
> +calcula_hora <- function(time_init, current_time) {
Seria bacana ter uma documentação simples do que a função faz.

2021-05-14 15:59 UTC, gileadekelvin approved these changes

2021-05-17 20:28 UTC, gileadekelvin approved these changes

2021-05-18 17:53 UTC, merged